
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author simon
 */
public class Interfaz extends javax.swing.JFrame {
    protected GrafoMAdy grafox;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPane = new javax.swing.JTabbedPane();
        MenuPanel = new javax.swing.JPanel();
        cargararchivo = new javax.swing.JButton();
        disponibilidad = new javax.swing.JButton();
        realizarpedido = new javax.swing.JButton();
        gestion = new javax.swing.JButton();
        grafo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cargartxtpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        archivotxt = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        select = new javax.swing.JButton();
        disponibilidadpanel = new javax.swing.JPanel();
        pedidopanel = new javax.swing.JPanel();
        gestionpanel = new javax.swing.JPanel();
        GrafoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cargararchivo.setText("Cargar Archivo ");
        cargararchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargararchivoActionPerformed(evt);
            }
        });

        disponibilidad.setText("Disponibilidad de Productos ");
        disponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disponibilidadActionPerformed(evt);
            }
        });

        realizarpedido.setText("Realizar Pedido ");
        realizarpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarpedidoActionPerformed(evt);
            }
        });

        gestion.setText("Gestion de Alamacenes");
        gestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionActionPerformed(evt);
            }
        });

        grafo.setText("Grafo ");
        grafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grafoActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(cargararchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(disponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(realizarpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(gestion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(grafo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(610, 610, 610)
                .addComponent(jButton1))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(cargararchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(disponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(realizarpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(gestion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(grafo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1))
        );

        TabbedPane.addTab("Menu", MenuPanel);

        cargartxtpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        archivotxt.setColumns(20);
        archivotxt.setRows(5);
        jScrollPane1.setViewportView(archivotxt);

        cargartxtpanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 71, 327, 194));

        jLabel2.setText("Seleccione el archivo de texto al cual le desea cargar los datos.");
        cargartxtpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 16, -1, 43));

        select.setText("seleccionar");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        cargartxtpanel.add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 71, 120, -1));

        TabbedPane.addTab("Cargar Archivo ", cargartxtpanel);

        disponibilidadpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        TabbedPane.addTab("Disponibilidad", disponibilidadpanel);

        pedidopanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        TabbedPane.addTab("Pedido", pedidopanel);

        gestionpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        TabbedPane.addTab("Gestion Alamacenes ", gestionpanel);

        javax.swing.GroupLayout GrafoPanelLayout = new javax.swing.GroupLayout(GrafoPanel);
        GrafoPanel.setLayout(GrafoPanelLayout);
        GrafoPanelLayout.setHorizontalGroup(
            GrafoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );
        GrafoPanelLayout.setVerticalGroup(
            GrafoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        TabbedPane.addTab("Grafo", GrafoPanel);

        jLabel1.setText("EQUIPO SUR ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargararchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargararchivoActionPerformed
        TabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_cargararchivoActionPerformed

    private void disponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disponibilidadActionPerformed

        TabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_disponibilidadActionPerformed

    private void realizarpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarpedidoActionPerformed
        TabbedPane.setSelectedIndex(3);
    }//GEN-LAST:event_realizarpedidoActionPerformed

    private void gestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionActionPerformed
        TabbedPane.setSelectedIndex(4);
    }//GEN-LAST:event_gestionActionPerformed

    private void grafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grafoActionPerformed
        TabbedPane.setSelectedIndex(5);
    }//GEN-LAST:event_grafoActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
         Archivo a = new Archivo();
        
        
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        File archivo = fc.getSelectedFile();
        
        if((archivo.getName()).contains(".txt")){
        String filename = archivo.getPath();     

        grafox = a.armarGrafo(filename);

            if(grafox != null){
            
                try{
                    FileReader fr = new FileReader (archivo);
                    BufferedReader br = new BufferedReader(fr);
                    String texto = "";
                    String linea = "";
                    while(((linea = br.readLine())!=null)){
                        texto+= linea+"\n";
                    }
                    archivotxt.setText(texto);
                    JOptionPane.showMessageDialog(null, "Archivo leido correctamente");
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "No se pudo leer el archivo");
                    }
                }
            
            else{
                JOptionPane.showMessageDialog(null, "Ingrese un archivo válido");
            }
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Error, no es archivo txt. Ingrese un archivo válido");
        }
        
    }//GEN-LAST:event_selectActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GrafoPanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JTextArea archivotxt;
    private javax.swing.JButton cargararchivo;
    private javax.swing.JPanel cargartxtpanel;
    private javax.swing.JButton disponibilidad;
    private javax.swing.JPanel disponibilidadpanel;
    private javax.swing.JButton gestion;
    private javax.swing.JPanel gestionpanel;
    private javax.swing.JButton grafo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pedidopanel;
    private javax.swing.JButton realizarpedido;
    private javax.swing.JButton select;
    // End of variables declaration//GEN-END:variables
}
