
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author simon
 * @version 03/06/2022
 */
public class Interfaz extends javax.swing.JFrame {
    protected GrafoMAdy grafox = null;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPane = new javax.swing.JTabbedPane();
        MenuPanel = new javax.swing.JPanel();
        cargararchivo = new javax.swing.JButton();
        disponibilidad = new javax.swing.JButton();
        realizarpedido = new javax.swing.JButton();
        gestion = new javax.swing.JButton();
        grafo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cargartxtpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        archivotxt = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        select = new javax.swing.JButton();
        volverCarga = new javax.swing.JButton();
        disponibilidadpanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        dispoOrigen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bRecorrer = new javax.swing.JButton();
        volverDispo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputAnchura = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        outputProfundidad = new javax.swing.JTextPane();
        pedidopanel = new javax.swing.JPanel();
        gestionpanel = new javax.swing.JPanel();
        GrafoPanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabbedPane.setBackground(new java.awt.Color(51, 153, 255));

        MenuPanel.setBackground(new java.awt.Color(51, 153, 255));
        MenuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cargararchivo.setBackground(new java.awt.Color(255, 204, 51));
        cargararchivo.setText("Cargar Archivo ");
        cargararchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargararchivoActionPerformed(evt);
            }
        });
        MenuPanel.add(cargararchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 200, 40));

        disponibilidad.setBackground(new java.awt.Color(255, 204, 51));
        disponibilidad.setText("Disponibilidad de Productos ");
        disponibilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disponibilidadActionPerformed(evt);
            }
        });
        MenuPanel.add(disponibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 200, 40));

        realizarpedido.setBackground(new java.awt.Color(255, 204, 51));
        realizarpedido.setText("Realizar Pedido ");
        realizarpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarpedidoActionPerformed(evt);
            }
        });
        MenuPanel.add(realizarpedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 200, 40));

        gestion.setBackground(new java.awt.Color(255, 204, 51));
        gestion.setText("Gestion de Alamacenes");
        gestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionActionPerformed(evt);
            }
        });
        MenuPanel.add(gestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 200, 40));

        grafo.setBackground(new java.awt.Color(255, 204, 51));
        grafo.setText("Grafo ");
        grafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grafoActionPerformed(evt);
            }
        });
        MenuPanel.add(grafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 200, 40));

        jButton1.setBackground(new java.awt.Color(255, 204, 51));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        MenuPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/airplane2.0.png"))); // NOI18N
        MenuPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, 260));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setText("Welcome to Surazon.com");
        MenuPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 250, -1));

        TabbedPane.addTab("Menu", MenuPanel);

        cargartxtpanel.setBackground(new java.awt.Color(51, 153, 255));
        cargartxtpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        archivotxt.setColumns(20);
        archivotxt.setRows(5);
        jScrollPane1.setViewportView(archivotxt);

        cargartxtpanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 71, 327, 194));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setText("Seleccione el archivo de texto al cual le desea cargar los datos...");
        cargartxtpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 16, -1, 43));

        select.setBackground(new java.awt.Color(255, 204, 51));
        select.setText("seleccionar");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        cargartxtpanel.add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 71, 120, -1));

        volverCarga.setBackground(new java.awt.Color(255, 204, 51));
        volverCarga.setText("Volver");
        volverCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverCargaActionPerformed(evt);
            }
        });
        cargartxtpanel.add(volverCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, -1, 30));

        TabbedPane.addTab("Cargar Archivo ", cargartxtpanel);

        disponibilidadpanel.setBackground(new java.awt.Color(51, 153, 255));
        disponibilidadpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel4.setText("Ingrese el almacén de origen:");
        disponibilidadpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        disponibilidadpanel.add(dispoOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 60, 40));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel3.setText("Recorrido de profundidad");
        disponibilidadpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel5.setText("Recorrido en anchura");
        disponibilidadpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        bRecorrer.setBackground(new java.awt.Color(255, 204, 51));
        bRecorrer.setText("Recorrer almacenes");
        bRecorrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRecorrerActionPerformed(evt);
            }
        });
        disponibilidadpanel.add(bRecorrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 170, 80));

        volverDispo.setBackground(new java.awt.Color(255, 204, 51));
        volverDispo.setText("Volver");
        volverDispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverDispoActionPerformed(evt);
            }
        });
        disponibilidadpanel.add(volverDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 30));

        jScrollPane2.setViewportView(outputAnchura);

        disponibilidadpanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 170, 250));

        jScrollPane3.setViewportView(outputProfundidad);

        disponibilidadpanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 170, 250));

        TabbedPane.addTab("Disponibilidad", disponibilidadpanel);

        pedidopanel.setBackground(new java.awt.Color(51, 153, 255));
        pedidopanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        TabbedPane.addTab("Pedido", pedidopanel);

        gestionpanel.setBackground(new java.awt.Color(51, 153, 255));
        gestionpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        TabbedPane.addTab("Gestion Alamacenes ", gestionpanel);

        GrafoPanel.setBackground(new java.awt.Color(51, 153, 255));

        jButton2.setBackground(new java.awt.Color(255, 204, 51));
        jButton2.setText("Dibujar Grafo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setText("Para visualizar el grafo por favor oprima el boton...");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/map.png"))); // NOI18N

        javax.swing.GroupLayout GrafoPanelLayout = new javax.swing.GroupLayout(GrafoPanel);
        GrafoPanel.setLayout(GrafoPanelLayout);
        GrafoPanelLayout.setHorizontalGroup(
            GrafoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GrafoPanelLayout.createSequentialGroup()
                .addGroup(GrafoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GrafoPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel7))
                    .addGroup(GrafoPanelLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel9)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        GrafoPanelLayout.setVerticalGroup(
            GrafoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GrafoPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addGroup(GrafoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GrafoPanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GrafoPanelLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel9)))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Grafo", GrafoPanel);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargararchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargararchivoActionPerformed
        TabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_cargararchivoActionPerformed

    private void disponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disponibilidadActionPerformed

        TabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_disponibilidadActionPerformed

    private void realizarpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarpedidoActionPerformed
        TabbedPane.setSelectedIndex(3);
    }//GEN-LAST:event_realizarpedidoActionPerformed

    private void gestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionActionPerformed
        TabbedPane.setSelectedIndex(4);
    }//GEN-LAST:event_gestionActionPerformed

    private void grafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grafoActionPerformed
        TabbedPane.setSelectedIndex(5);
    }//GEN-LAST:event_grafoActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
         Archivo a = new Archivo();
        
        
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        File archivo = fc.getSelectedFile();
        
        if((archivo.getName()).contains(".txt")){
        String filename = archivo.getPath();     

        grafox = a.armarGrafo(filename);

            if(grafox != null){
            
                try{
                    FileReader fr = new FileReader (archivo);
                    BufferedReader br = new BufferedReader(fr);
                    String texto = "";
                    String linea = "";
                    while(((linea = br.readLine())!=null)){
                        texto+= linea+"\n";
                    }
                    archivotxt.setText(texto);
                    JOptionPane.showMessageDialog(null, "Archivo leido correctamente");
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "No se pudo leer el archivo");
                    }
                }
            
            else{
                JOptionPane.showMessageDialog(null, "Ingrese un archivo válido");
            }
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Error, no es archivo txt. Ingrese un archivo válido");
        }
        
    }//GEN-LAST:event_selectActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void volverDispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverDispoActionPerformed
        TabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_volverDispoActionPerformed

    private void bRecorrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRecorrerActionPerformed
        String temp = "";
        
        if(grafox != null){
            try{
                String origen = dispoOrigen.getText();

                temp = Recorrido.recorrerAnchura(grafox, origen);

                outputAnchura.setText(temp);


                temp = Recorrido.recorrerProfundidad(grafox, origen);
                
                outputProfundidad.setText(temp);

            }catch(Exception e){

                JOptionPane.showMessageDialog(null, "Error, recorrido fallido");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Error, no ha cargado la información.");
        }
    }//GEN-LAST:event_bRecorrerActionPerformed

    private void volverCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverCargaActionPerformed
        TabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_volverCargaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        GraficarGrafo s = new GraficarGrafo(); 
        s.mostrar();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GrafoPanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JTextArea archivotxt;
    private javax.swing.JButton bRecorrer;
    private javax.swing.JButton cargararchivo;
    private javax.swing.JPanel cargartxtpanel;
    private javax.swing.JTextField dispoOrigen;
    private javax.swing.JButton disponibilidad;
    private javax.swing.JPanel disponibilidadpanel;
    private javax.swing.JButton gestion;
    private javax.swing.JPanel gestionpanel;
    private javax.swing.JButton grafo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane outputAnchura;
    private javax.swing.JTextPane outputProfundidad;
    private javax.swing.JPanel pedidopanel;
    private javax.swing.JButton realizarpedido;
    private javax.swing.JButton select;
    private javax.swing.JButton volverCarga;
    private javax.swing.JButton volverDispo;
    // End of variables declaration//GEN-END:variables
}
